indiviual_position_values = [
    {"character": "A", "value": 1},
    {"character": "B", "value": 0},
    {"character": "C", "value": 5},
    {"character": "D", "value": 7},
    {"character": "E", "value": 9},
    {"character": "F", "value": 13},
    {"character": "G", "value": 15},
    {"character": "H", "value": 17},
    {"character": "I", "value": 19},
    {"character": "J", "value": 21},
    {"character": "K", "value": 2},
    {"character": "L", "value": 4},
    {"character": "M", "value": 18},
    {"character": "N", "value": 20},
    {"character": "O", "value": 11},
    {"character": "P", "value": 3},
    {"character": "Q", "value": 6},
    {"character": "R", "value": 8},
    {"character": "S", "value": 12},
    {"character": "T", "value": 14},
    {"character": "U", "value": 16},
    {"character": "V", "value": 10},
    {"character": "W", "value": 22},
    {"character": "X", "value": 25},
    {"character": "Y", "value": 24},
    {"character": "Z", "value": 23},
    {"character": "0", "value": 1},
    {"character": "1", "value": 0},
    {"character": "2", "value": 5},
    {"character": "3", "value": 7},
    {"character": "4", "value": 9},
    {"character": "5", "value": 13},
    {"character": "6", "value": 15},
    {"character": "7", "value": 17},
    {"character": "8", "value": 19},
    {"character": "9", "value": 21}
]

even_position_values = [
    {"character": "A", "value": 0},
    {"character": "B", "value": 1},
    {"character": "C", "value": 2},
    {"character": "D", "value": 3},
    {"character": "E", "value": 4},
    {"character": "F", "value": 5},
    {"character": "G", "value": 6},
    {"character": "H", "value": 7},
    {"character": "I", "value": 8},
    {"character": "J", "value": 9},
    {"character": "K", "value": 10},
    {"character": "L", "value": 11},
    {"character": "M", "value": 12},
    {"character": "N", "value": 13},
    {"character": "O", "value": 14},
    {"character": "P", "value": 15},
    {"character": "Q", "value": 16},
    {"character": "R", "value": 17},
    {"character": "S", "value": 18},
    {"character": "T", "value": 19},
    {"character": "U", "value": 20},
    {"character": "V", "value": 21},
    {"character": "W", "value": 22},
    {"character": "X", "value": 23},
    {"character": "Y", "value": 24},
    {"character": "Z", "value": 25},
    {"character": "0", "value": 0},
    {"character": "1", "value": 1},
    {"character": "2", "value": 2},
    {"character": "3", "value": 3},
    {"character": "4", "value": 4},
    {"character": "5", "value": 5},
    {"character": "6", "value": 6},
    {"character": "7", "value": 7},
    {"character": "8", "value": 8},
    {"character": "9", "value": 9}
]


alpha_latin = [
    "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", 
    "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", 
    "U", "V", "W", "X", "Y", "Z"
]
